import { NextRequest, NextResponse } from "next/server";
import type { NotificationType } from "@/lib/water/mockSchedules";
import { notificationTypeLabel } from "@/lib/water/mockSchedules";

interface NotificationPayload {
  zone: string;
  type: NotificationType;
  customMessage?: string;
  time?: string;
}

// ---------------------------------------------------------------------------
// POST /api/water/notifications — send a demo notification email via Resend
// ---------------------------------------------------------------------------
export async function POST(req: NextRequest) {
  let body: NotificationPayload;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { zone, type, customMessage, time } = body;
  if (!zone || !type) {
    return NextResponse.json(
      { error: "zone and type are required" },
      { status: 400 },
    );
  }

  const apiKey = process.env.RESEND_API_KEY;
  const toEmail = process.env.WATER_DEMO_EMAIL;

  // -------------------------------------------------------------------------
  // Build the message text
  // -------------------------------------------------------------------------
  const typeLabel = notificationTypeLabel(type);
  const now = new Date().toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    dateStyle: "medium",
    timeStyle: "short",
  });

  let messageBody = "";
  if (type === "cutoff-today") {
    messageBody = `Water supply to ${zone} zone will be CUT OFF today${time ? ` from ${time}` : ""}. Please store adequate water.`;
  } else if (type === "supply-diverted") {
    messageBody = `Water supply to ${zone} zone will be DIVERTED tomorrow${time ? ` from ${time}` : ""}. Reduced pressure expected.`;
  } else if (type === "supply-resuming") {
    messageBody = `Water supply to ${zone} zone is RESUMING${time ? ` at ${time}` : " shortly"}. Normal pressure will be restored.`;
  } else {
    messageBody = customMessage ?? `Notice from BWSSB for ${zone} zone.`;
  }

  // -------------------------------------------------------------------------
  // Send via Resend if API key is configured
  // -------------------------------------------------------------------------
  if (!apiKey || !toEmail) {
    // Graceful degradation — return success without actually sending
    return NextResponse.json({
      sent: false,
      simulated: true,
      message: "RESEND_API_KEY or WATER_DEMO_EMAIL not configured — email simulated",
      preview: { zone, type: typeLabel, body: messageBody, sentAt: now },
    });
  }

  try {
    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "BWSSB Demo <onboarding@resend.dev>",
        to: [toEmail],
        subject: `[BWSSB DEMO] ${typeLabel} — ${zone} Zone`,
        html: `
          <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; background: #0b0f19; color: #e2e8f0; border-radius: 12px; overflow: hidden;">
            <div style="background: #06b6d4; padding: 20px 24px;">
              <h1 style="margin: 0; font-size: 18px; color: #000;">BWSSB Water Notification</h1>
              <p style="margin: 4px 0 0; font-size: 12px; color: #00000099;">Demo / Hackathon Mode — Not a real alert</p>
            </div>
            <div style="padding: 24px;">
              <p style="margin: 0 0 8px; font-size: 20px; font-weight: 700; color: #06b6d4;">${typeLabel}</p>
              <p style="font-size: 13px; color: #94a3b8; margin: 0 0 16px;">Zone: <strong style="color: #e2e8f0;">${zone}</strong></p>
              <p style="font-size: 15px; line-height: 1.6; margin: 0 0 24px;">${messageBody}</p>
              <hr style="border: none; border-top: 1px solid #1e293b; margin: 16px 0;" />
              <p style="font-size: 12px; color: #64748b; margin: 0;">
                Sent by Municipality Dashboard · ${now}<br/>
                <em>This is a demo notification generated by CityPulse AI for a college project. No real water supply is affected.</em>
              </p>
            </div>
          </div>
        `,
      }),
      signal: AbortSignal.timeout(10_000),
    });

    if (!emailRes.ok) {
      const errText = await emailRes.text();
      throw new Error(`Resend API ${emailRes.status}: ${errText}`);
    }

    const emailData = (await emailRes.json()) as { id?: string };

    return NextResponse.json({
      sent: true,
      simulated: false,
      emailId: emailData.id,
      to: toEmail,
      preview: { zone, type: typeLabel, body: messageBody, sentAt: now },
    });
  } catch (err) {
    console.error("[/api/water/notifications] Resend error:", err);
    return NextResponse.json(
      {
        sent: false,
        simulated: true,
        error: err instanceof Error ? err.message : "Email send failed",
        preview: { zone, type: typeLabel, body: messageBody, sentAt: now },
      },
      { status: 200 }, // Return 200 so the UI can show a graceful message
    );
  }
}
