"use client";

import { Sparkles } from "lucide-react";

export default function GemmaAttribution({ className = "" }: { className?: string }) {
  return (
    <span
      className={`inline-flex items-center gap-1 text-[10px] uppercase tracking-wide text-accent/80 ${className}`}
      title="Reasoning generated by Gemma from ward facts and/or retrieved precedent"
    >
      <Sparkles className="w-3 h-3" />
      Gemma
    </span>
  );
}
